# Generated by Django 3.2.2 on 2021-05-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='performer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
