# Generated by Django 3.2.2 on 2021-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210512_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Мой плейлист', max_length=100),
        ),
    ]
