export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST'   
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS'
export const PLAYLIST_FAIL = 'PLAYLIST_FAIL'


export const PLAYLIST_DETAIL_REQUEST = 'PLAYLIST_DETAIL_REQUEST'
export const PLAYLIST_DETAIL_SUCCESS = 'PLAYLIST_DETAIL_SUCCESS'
export const PLAYLIST_DETAIL_FAIL = 'PLAYLIST_DETAIL_FAIL'

export const PLAYLIST_FETCHING_REQUEST = 'PLAYLIST_FETCHING_REQUEST'
export const PLAYLIST_FETCHING_SUCCESS = 'PLAYLIST_FETCHING_SUCCESS'
export const PLAYLIST_FETCHING_FAIL = 'PLAYLIST_FETCHING_FAIL'

export const PLAYLIST_CREATING_REQUEST = 'PLAYLIST_CREATING_REQUEST'
export const PLAYLIST_CREATING_SUCCESS = 'PLAYLIST_CREATING_SUCCESS'
export const PLAYLIST_CREATING_FAIL = 'PLAYLIST_CREATING_FAIL'

export const PLAYLIST_DELETING_REQUEST = 'PLAYLIST_DELETING_REQUEST'
export const PLAYLIST_DELETING_SUCCESS = 'PLAYLIST_DELETING_SUCCESS'
export const PLAYLIST_DELETING_FAIL = 'PLAYLIST_DELETING_FAIL'

export const SEARCHING_SONG = 'SEARCHING_SONG'

