export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST'
        
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS'

export const PLAYLIST_FAIL = 'PLAYLIST_FAIL'


export const PLAYLIST_DETAIL_REQUEST = 'PLAYLIST_DETAIL_REQUEST'
        
export const PLAYLIST_DETAIL_SUCCESS = 'PLAYLIST_DETAIL_SUCCESS'

export const PLAYLIST_DETAIL_FAIL = 'PLAYLIST_DETAIL_FAIL'